---
- name: RUN
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Enable JWT Auth
    uri:
      url: "{{ lookup('env', 'VAULT_ADDR') }}/v1/sys/auth/jwt"
      headers:
        X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
      body_format: json
      method: POST
      body:
        type: jwt
      status_code: [204,400]
    register: vault_auth_enable
    changed_when: vault_auth_enable.status == 204